version: '3.8'

volumes:
    alfasoft-data:
        driver: local

services:
    database:
        image: mysql:5.7
        container_name: database
        environment:
            - MYSQL_HOST=mariadb
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=recruitment
            - MYSQL_USER=luizmedina
            - MYSQL_PASSWORD=abc123
        ports:
            - '3306:3306'
        volumes:
            - alfasoft-data:/var/lib/mysql

    server:
        build: .
        container_name: server
        ports:
            - '8000:8000'
        volumes:
            - .:/var/www/html/
            - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        links:
            - database
